### ISSUE TITLE
Make always build from $GOPATH/src/github.com/kubeapps/installer, even if you downloaded the code elsewhere

### ISSUE THREAD

**Issue by arapulido** [kubeapps/installer#22]
Steps to reproduce:

1. Git clone into a path outside GOPATH
2. cd and make

Expected results:
make finishes successfully and gets the code from $PWD

Actual results:
Build fails or builds from $GOPATH/src/github.com/kubeapps/installer if that exists

**Comment by ngtuna** [comment]
I agree with the failed case but I don't really think we should support to build the project outside of $GOPATH. As a small project, we should be just like a normal golang project (with the constraint to put it in a correct path `$GOPATH/src/path/to/repo`). I asked @anguslees and he also agreed. I think updating README.md to mention that would be better.

**Comment by arapulido** [comment]
Closing, as the building instructions are now fixed
