### ISSUE TITLE
Use different debug levels

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/installer#31]
Right know the logs are a bit confusing. For example:
```
▶ ./kubeapps up
INFO[0000] Updating namespaces kubeapps
INFO[0000]  Creating non-existent namespaces kubeapps
INFO[0000] Updating namespaces kubeless
INFO[0002] Updating namespaces kubeless
INFO[0002] Updating namespaces kubeapps
```
Why is it updating a namespace several times?

Also it seems that we can benefit from using different log levels. Right now everything is at the "INFO" log level. A general deployment doesn't require that level of detail so we can use "DEBUG" for most of the current logs and only print it when using `--verbose`

BTW, a final message once everything is installed like:
```
... 
[INFO] Finished deployment. Execute `kubectl proxy` and open the Kubeapps Dashboard at <calculated_url>
```
(or `... Execute "kubeapps dashboard" ...` when that command is ready)

**Comment by arapulido** [comment]
This is now fixed with PR #34
